import 'package:flutter/material.dart';
import 'package:sizer/sizer.dart';
import 'package:banjarabio/l10n/app_localizations.dart';
import 'package:banjarabio/core/app_export.dart';
import 'package:banjarabio/core/models/success_story_model.dart';
import 'package:banjarabio/core/repositories/success_story_repository.dart';
import 'package:banjarabio/core/repositories/subscription_repository.dart';
import 'package:banjarabio/widgets/custom_app_bar.dart';


class MarriageRewardFormScreen extends StatefulWidget {
  const MarriageRewardFormScreen({super.key});

  @override
  State<MarriageRewardFormScreen> createState() => _MarriageRewardFormScreenState();
}

class _MarriageRewardFormScreenState extends State<MarriageRewardFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final _storyController = TextEditingController();
  final _partnerNameController = TextEditingController();
  final _instagramLinkController = TextEditingController();
  
  MarriageRewardType _rewardType = MarriageRewardType.digital25;
  DateTime _weddingDate = DateTime.now().add(const Duration(days: 30));
  double _subscriptionAmount = 0.0;
  bool _isLoading = true;
  bool _isSubmitting = false;

  @override
  void initState() {
    super.initState();
    _loadSubscriptionDetails();
  }

  Future<void> _loadSubscriptionDetails() async {
    final subRes = await SubscriptionRepository().getCurrentSubscription();
    subRes.fold(
      onSuccess: (sub) {
        if (mounted) {
          setState(() {
            _subscriptionAmount = sub?.amountPaid?.toDouble() ?? 0.0;
            _isLoading = false;
          });
        }
      },
      onFailure: (_) => setState(() => _isLoading = false),
    );
  }

  void _handleSubmit() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isSubmitting = true);

    final story = SuccessStoryModel(
      id: '', // Will be generated by DB
      userId: SessionManager.instance.profileId ?? '',
      partnerName: _partnerNameController.text.trim(),
      storyText: _storyController.text.trim(),
      instagramLink: _instagramLinkController.text.trim(),
      weddingDate: _weddingDate,
      subscriptionAmount: _subscriptionAmount,
      type: _rewardType,
      createdAt: DateTime.now(),
    );

    final res = await SuccessStoryRepository().submitSuccessStory(story);

    if (mounted) {
      res.fold(
        onSuccess: (_) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text(AppLocalizations.of(context)?.successSubmission ?? 'Success! Your request has been submitted for review.')),
          );
          Navigator.pop(context);
        },
        onFailure: (error) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Failed: $error')),
          );
        },
      );
      setState(() => _isSubmitting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final l10n = AppLocalizations.of(context);

    if (_isLoading) {
      return const Scaffold(body: Center(child: CircularProgressIndicator()));
    }

    final refundAmount = _subscriptionAmount * (_rewardType == MarriageRewardType.digital25 ? 0.25 : 0.35);

    return Scaffold(
      appBar: CustomAppBar(title: l10n?.claimMarriageGift ?? 'Claim Marriage Gift'),
      body: SingleChildScrollView(
        padding: EdgeInsets.all(4.w),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildRewardTierCard(theme),
              SizedBox(height: 3.h),
              Text(
                l10n?.tellUsYourStory ?? 'Tell us your Story',
                style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 1.h),
              TextFormField(
                controller: _partnerNameController,
                decoration: InputDecoration(
                  labelText: l10n?.partnerName ?? "Partner's Name",
                  border: const OutlineInputBorder(),
                ),
                validator: (v) => v!.isEmpty ? 'Required' : null,
              ),
              SizedBox(height: 2.h),
              TextFormField(
                controller: _storyController,
                maxLines: 4,
                decoration: InputDecoration(
                  labelText: l10n?.yourSuccessStory ?? 'Your Success Story',
                  hintText: l10n?.howDidYouMeet ?? 'How did you meet? What do you like about them?',
                  border: const OutlineInputBorder(),
                ),
              ),
              SizedBox(height: 3.h),
              Text(
                l10n?.proofOfMarriage ?? 'Proof of Marriage',
                style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 1.h),
              TextFormField(
                controller: _instagramLinkController,
                decoration: InputDecoration(
                  labelText: l10n?.instagramLink ?? 'Instagram Reel/Story Link',
                  hintText: l10n?.pasteUrlHere ?? 'Paste the URL here',
                  border: const OutlineInputBorder(),
                ),
                validator: (v) => v!.isEmpty ? 'Link required for refund' : null,
              ),
              SizedBox(height: 2.h),
              ListTile(
                title: Text(l10n?.weddingDate ?? 'Wedding Date'),
                subtitle: Text('${_weddingDate.day}/${_weddingDate.month}/${_weddingDate.year}'),
                trailing: const Icon(Icons.calendar_today),
                onTap: () async {
                  final date = await showDatePicker(
                    context: context,
                    initialDate: _weddingDate,
                    firstDate: DateTime(2020),
                    lastDate: DateTime(2030),
                  );
                  if (date != null) setState(() => _weddingDate = date);
                },
              ),
              SizedBox(height: 4.h),
              Container(
                padding: EdgeInsets.all(4.w),
                decoration: BoxDecoration(
                  color: Colors.green.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: Colors.green.withValues(alpha: 0.3)),
                ),
                child: Row(
                  children: [
                    const Icon(Icons.card_giftcard, color: Colors.green),
                    SizedBox(width: 3.w),
                    Expanded(
                      child: Text(
                        '${l10n?.estimatedRefund ?? 'Estimated Refund'}: ₹${refundAmount.toStringAsFixed(0)}',
                        style: theme.textTheme.titleMedium?.copyWith(
                          color: Colors.green,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              SizedBox(height: 4.h),
              SizedBox(
                width: double.infinity,
                height: 55,
                child: ElevatedButton(
                  onPressed: _isSubmitting ? null : _handleSubmit,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: theme.primaryColor,
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  ),
                  child: _isSubmitting 
                    ? const CircularProgressIndicator(color: Colors.white)
                    : Text(l10n?.submitForReview ?? 'SUBMIT FOR REVIEW', style: const TextStyle(fontWeight: FontWeight.bold)),
                ),
              ),
              SizedBox(height: 4.h),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildRewardTierCard(ThemeData theme) {
    final l10n = AppLocalizations.of(context);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          l10n?.selectRewardType ?? 'Select Reward Type',
          style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.bold),
        ),
        SizedBox(height: 1.h),
        Row(
          children: [
            Expanded(
              child: _buildTierOption(
                l10n?.digital ?? 'Digital',
                l10n?.refund25 ?? '25% Refund',
                MarriageRewardType.digital25,
                Icons.video_library,
                l10n,
              ),
            ),
            SizedBox(width: 2.w),
            Expanded(
              child: _buildTierOption(
                l10n?.teamVisit ?? 'Team Visit',
                l10n?.refund35 ?? '35% Refund',
                MarriageRewardType.fullInvitation35,
                Icons.mail,
                l10n,
              ),
            ),
          ],
        ),
      ],
    );
  }

  Widget _buildTierOption(String title, String subtitle, MarriageRewardType type, IconData icon, AppLocalizations? l10n) {
    final isSelected = _rewardType == type;
    final theme = Theme.of(context);
    
    return GestureDetector(
      onTap: () => setState(() => _rewardType = type),
      child: Container(
        padding: EdgeInsets.all(3.w),
        decoration: BoxDecoration(
          color: isSelected ? theme.primaryColor : theme.cardColor,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
            color: isSelected ? theme.primaryColor : theme.dividerColor,
            width: 2,
          ),
        ),
        child: Column(
          children: [
            Icon(icon, color: isSelected ? Colors.white : theme.primaryColor),
            SizedBox(height: 1.h),
            Text(
              title,
              style: TextStyle(
                color: isSelected ? Colors.white : theme.colorScheme.onSurface,
                fontWeight: FontWeight.bold,
              ),
            ),
            Text(
              subtitle,
              style: TextStyle(
                color: isSelected ? Colors.white.withValues(alpha: 0.8) : theme.colorScheme.onSurfaceVariant,
                fontSize: 10.sp,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
