// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIP78p9S-99iLGfUdU6zYLRV9TwU8zWxk',
    appId: '1:1026269288051:web:7cf0fef8bd252f6f5a3c06',
    messagingSenderId: '1026269288051',
    projectId: 'banjarabio-8818a',
    authDomain: 'banjarabio-8818a.firebaseapp.com',
    storageBucket: 'banjarabio-8818a.firebasestorage.app',
    measurementId: 'G-HRLKJB6RMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoyVca6h24PDVwcnIrTuQR19RKrteEwiA',
    appId: '1:1026269288051:android:c0ad242cfe119ee15a3c06',
    messagingSenderId: '1026269288051',
    projectId: 'banjarabio-8818a',
    storageBucket: 'banjarabio-8818a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjY_oHym9Uu8c-j2UhDsUwwb4S2BBKvAs',
    appId: '1:1026269288051:ios:b20ba7aa84ad70de5a3c06',
    messagingSenderId: '1026269288051',
    projectId: 'banjarabio-8818a',
    storageBucket: 'banjarabio-8818a.firebasestorage.app',
    iosBundleId: 'com.avishio.banjarabio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjY_oHym9Uu8c-j2UhDsUwwb4S2BBKvAs',
    appId: '1:1026269288051:ios:b20ba7aa84ad70de5a3c06',
    messagingSenderId: '1026269288051',
    projectId: 'banjarabio-8818a',
    storageBucket: 'banjarabio-8818a.firebasestorage.app',
    iosBundleId: 'com.avishio.banjarabio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIP78p9S-99iLGfUdU6zYLRV9TwU8zWxk',
    appId: '1:1026269288051:web:52fa46ab931119075a3c06',
    messagingSenderId: '1026269288051',
    projectId: 'banjarabio-8818a',
    authDomain: 'banjarabio-8818a.firebaseapp.com',
    storageBucket: 'banjarabio-8818a.firebasestorage.app',
    measurementId: 'G-2DT79745HL',
  );
}
